### ISSUE TITLE
Documentation issue for user configuration

### ISSUE THREAD

**Issue by thomasmattheussen** [AdamLeBlanc/storybook-addon-dark-mode-toggle#1]
Hi, thanks for this plugin!

I think there's an error in the documentation though on how to supply your user configuration in `preview.js`. I had to read the source code to see why it wasn't working.

In `src/constants.ts` the `PARAM_KEY` is set to `data-theme-toggle` but in the README you don't set this param key in the export parameters for `preview.js`.

I believe it should be

```javascript
export const parameters = {
  'data-theme-toggle': {
    ...
  },
};
```
instead of
```javascript
export const parameters = {
  ...
};
```

**Comment by AdamLeBlanc** [comment]
Yes, you are correct. I will add that to my todo list for the week. 

I also have to update the plugin for SB 7 at some point, so maybe I'll get the motivation to do that this week when I fix this 😅
